# Data 

## Diet data: <br> National Food Survey <br> (1974 to 2000)

All dietary data for this project originates from the UK government's National Food Survey (NFS).

The NFS started in 1940 and eventually evolved into the Living Costs and Food Survey, which is active in 2026. However, not all of the associated data is publicly available.

For interested parties with institutional credentials, the [UK Data Service](https://ukdataservice.ac.uk) does provide a curated batch of NFS data that spans from 1974-2000.  

In this data, approximately 7,000 households per year across the UK were chosen at random from voting roles and asked to participate by keeping a one week diet diary. From 1974 to 2000, almost 190,000 total households participated. 

Consenting households tracked all food purchases for one week, recording the consumable quantity (`cq`) of each purchase and assigning it to one of over 300 minor food codes (`minfd`). Each minor food code can be mapped to one of 184 major food codes (`majfd`).  

There are several native food group mappings included with the NFS data, but those food groupings tend to focus on economic details more than nutrition oriented details. 

An iterative manual review of all reported foods in the data was conducted, and a custom set of sixteen foodgroups was designated based on literature [@schulz_advances_2021; @perraud_plant_2022; @gaesser_whole_2020] in order to assess the data from a nutritional perspective. 

Each row in the diet diaries was assigned one of these custom food group labels, enabling food group profiling of each household. A full printout of the custom food group mappings is included in the Appendix .

Additionally, the NFS included annually adjusted nutrient conversion information for each of the minor food codes, allowing the recorded type and quantity to be converted into a nutrient profile for that purchase, and in turn aggregated to an overall nutrient profile for each household.

Demographic and economic information is also included with the NFS data. However, this analysis assesses diet composition per calorie, not diet quantity per capita.  While calorie-per-person-per-day was used to cull data-devoid households in the data cleaning (discussed below), the food group and nutrient profile metrics carried forward into the analysis are quantity-agnostic.

So, the only demographic information that was ultimately used in this analysis is the regional location of each household. 


## Disease data: <br> Global Burden of Disease <br> (1990 to 2023)

Population-level disease risk rates for High LDL cholesterol and other metabolic-disease associated risk factors were acquired from the Institute for Health Metrics and Evaluation (IHME), using their [Global Burden of Disease (GBD) Results tool](https://vizhub.healthdata.org/gbd-results/).

The specific metric chosen for disease risk rate was summary exposure value, or SEV.

[The IHME defines SEV](https://www.healthdata.org/sites/default/files/files/policy_report/GBD/2016/IHME_GBD2015_Report_Glossary-of-terms_2016.pdf) as a "... measure of a population’s exposure to a risk factor that takes into account the extent of exposure by risk level and the severity of that risk’s contribution to disease burden."

SEV appeared to be the best available metric from the GBD results tool to assess risk factor prevalance.  

From there, the chronic disease risk factors and conditions for which SEV information were metabolic risks: High LDL Cholesterol, High Body Mass Index, High Fasting Plasma Glucose Systolic Blood Pressure, Kidney Dysfunction, Low Bone Mineral Density, and overall Metabolic Risks. 

These risk rates were hand-selected and obtained preaggregted at a population level, grouped by UK region and by year.  For the scope of this project, all ages and both sexes were included in SEV information. 


## Dietary Data Engineering

#### Household food group profiles

For each diet diary row, calories were calculated based on NFS provided nutrient conversion factor for Energy (kCal) for the given food multiplied by the consumable quantity `cq` reported (@eq-row-calories).

$$
calories_{row} = cq_{row} \times \text{energy conversion factor}_{row}
$$ {#eq-row-calories}

 
Then, for each household, calories were aggregated for each of the assigned food groups, and then divided by total calories for that household.

$$
{calorie\_ratio}_{food group} = \frac{\text{total calories per food group}}{\text{total calories per household}}
$$ {#eq-food-groups-calorie-ratio}


This resulted in a 'calorie ratio' for each food group for that household for that week.  This normalized metric cancels out quantity, and purely examines the qualitative composition of each household's reported food acquisition for the week.  Therefore, the number of people in the household do not factor into this metric, and further demographic considerations did not need to be calculated.

Finally, calorie ratios for all food groups were normalized by Standard Scaler and z-scored, with the means set to zero and the standard deviations set to plus or minus one.

#### Household nutrient profiles

Total calories were calculated for each household as with the food group feature engineering.

Then, each minor food code `minfd` was converted to the nutrient profile for that food multiplied by the quantity reported `cq`. This effectively expanded each diary entry row into twenty rows, one for each of the twenty nutrients tracked throughout the data, with the appropriate unit quantity for each nutrient reported.  

$$
nutrient\_quantity_{row} = cq_{row} \times \text{nutrient conversion factor}_{row}
$$ {#eq-nutrient-calorie-ratio-3}

 Maintaining each nutrient's native unit (grams, milligrams, micrograms, etc.), the total quantity of each nutrient across all food purchases was aggregated for each household. Those quantities were then divided by total calories for that household.

$$
nutrient\_quantity\_per\_total\_cal_{row} =  \frac{\text{total quantity per nutrient}}{\text{total calories per household}}
$$ {#eq-nutrient-quantity-calorie-ratio-4}

The resultant nutrient profile metric, 'quantity per total calories,' is similar in spirit to the 'calorie-ratio' metric from the food groups. 

However, a pure calorie comparison for nutrients would not be viable, as certain nutrients (carbohydrates, fats) have abundant calories while other nutrients (vitamins) have essentially zero calories. Hence, native nutrient units were maintained and divided by the common total calories.  This might preclude comparison amongst nutrients, but this analysis assesses household nutrient profiles, so the variation in fundamental units was not problematic.

Furthermore, variations in magnitude amongst the derived nutrient-quantity-per-total-calorie unit was also subjected to the Standard Scaler and z-scored before analysis.


## Data Pipeline Overview <br> 

As described in detail below:

- Diet diary data was cleaned and aggregated by food group and by nutrient profile for each household in the dataset.
- This yielded a sixteen-dimensional food group vector and a twenty-dimensional nutrient vector for each household.  
- Those vectors were subjected to a machine learning pipeline that assigned a food group cluster label and a nutrient cluster label to each household.  Principle component analysis was used to understand and visualize the clustering.  
- Changing proportions of those clusters in the total population were assessed over time using a variety of statistical tests, in addition to visual inspection of time-based line plots.  
- Population-level SEV risk rates were then joined at varying time-lags on year and region.
- The year-on-year rate of change for a given cluster proportion was correlated with year-on-year rate of change for metabolic disease risk factors at varying time lags.   

### Diet data cleaning

The NFS evolved over time, and this evolution prompted several data cleaning decisions for this analysis.  

Alcohol, confectioneries, and soft drinks were added as reportable food options in 1992. It is presumed that some UK households did purchase alcohol, confectioneries, and soft drinks before 1992, but the diet diaries cannot show this.  All three categories are considered high-calorie, so their sudden appearance does skew calorie-adjusted calculations. In order to maintain consistency over time, all diet diary rows from these three categories were dropped from analysis, though the related households and all their other diet diary entries were retained.

Initial analysis before dropping alcohol had designated alcohol as its own food group, for 17 total food groups.  After dropping all alcohol rows, this analysis looked at 16 total foodgroups.

Northern Ireland was only included in the survey starting in 1996. In the interest of consistency, Northern Ireland households were excluded from this analysis altogether.

The nutrient conversion information evolved over time as well, tracking 21 nutrients in 1974 and over 40 nutrients by 2000.  As with pruning rows from late-added foods and locations, nutrient trends were only assessed for the nutrients that were tracked throughout the entire dataset.  

One of the included nutrients was Energy in MJ (megaJoules), which was collinear with Energy in kCal. Energy in MJ was dropped from nutrient analysis, resulting in 20 assessed nutrients.

The NFS and IHME data have a discrepancy in UK government office regions as well: the 1974 to 2000 NFS data list Merseyside as a distinct region, while the 1990 to 2023 IHME data includes that some geographical area as part of North West England.  So, before aggregation, all NFS households from Merseyside were reassigned as being part of North West England, for consistency between datasets.

A final cleaning step was to prune households that reported a physiologically unrealistic amount of calories, below a threshold that people require to live.  These households were considered to have provided unreliable data and were excluded from analysis.  The caloric floor threshold was set to two standard deviations below the mean of log-space per capita calorie intake, inspired by similar approaches in the literature [@black_critical_2000].  While the overall analysis does not rely on per capita calculations, this pruning step does. Per capita per household calculations were adjusted for age and sex (adult males = 1, adult females = 0.8, children = 0.5, elderly adults = 0.85), consistent with the literature [@noauthor_sacn_nodate].

### Diet data aggregation

Dietary data aggregation was undertaken to generate the features described with @eq-row-calories, @eq-food-groups-calorie-ratio, @eq-nutrient-calorie-ratio-3, and @eq-nutrient-quantity-calorie-ratio-4 above.

The raw download from the UK Data Service has a folder for each year between 1974 and 2000, with space separated text files for diet diary, household information, and nutrient conversion factors.  All years of the NFS data share minor to major food code look up tables with consistent food code descriptions.

#### Household food group profile aggregation

On a year by year basis, calorie-specific nutrient conversion information was joined to each row of the diet diary (on minor food code, `minfd`), multiplied by consumable quantity `cq`, and then summed per household to calculate total calories for that household (@eq-row-calories). Total household calories was later joined back to un-aggregated data as needed.

Minor food codes were mapped to major food codes, which were then mapped to custom food group labels (see Appendix).  Then each row was grouped by household and by foodgroup, aggregating total calories for each food group and for each household.  From there, every household could be assigned a proportion of total calories that was attributable to each foodgroup @eq-food-groups-calorie-ratio.

Household information was then joined on household number (`hhno`) to obtain the correct government office region for each household. 

Finally, each year's processed aggregated food group profile data was appended to a list of dataframes and vertically concatenated.


#### Household nutrient profile aggregation

Year by year, nutrient conversion information for all included nutrients was joined to each row of the diet diary (on minor food code, `minfd`), multiplied by consumable quantity `cq`, and then summed by household to calculate quantity of that nutrient for that household (@eq-nutrient-calorie-ratio-3).  This automatically included total calories for that household, which was then used to create quantity-per-total-calorie metrics for each household and each nutrient @eq-nutrient-quantity-calorie-ratio-4.

Household information was then joined on household number `hhno` to obtain the correct government office region `gor` for each household. 

Finally, each year's processed aggregated nutrient profile data was appended to a list of dataframes and vertically concatenated.


#### Machine Learning Pipeline

The data for both food group and nutrient profiles were pivoted to a wide format, with each household retaining a row, and each column becoming one of the foodgroups or nutrients.  The values in the wide pivot table were the household's calorie ratio or quantity-per-total-calorie for that food group or nutrient, respectively. The wide tables were then z-score normalized.

The machine learning pipeline (described in detail in the Analysis section) assigned food group profile cluster labels and nutrient profile cluster labels to each household.  

Proportions of each cluster type amongst all households were then plotted and assessed over time,  nationally and regionally.  Changes in these proportions is the fundamental explanatory variable of this analysis.


#### Joining disease data

Once food group and nutrient profile cluster labels were assigned and population-level proportions of those clusters were tracked over time, the IHME data with SEV rates for several metabolic risk factors was joined on region and year. 

Since this analysis assesses time-lag, the IHME data was joined across a sweep of lag years, so that for a given diet data year, columns for corresponding SEV rates for a range of lag years (zero years to up to 49 years) were added.


## Project scalability

The exact aggregation scripts that transform the raw diet diary data into usable machine learning inputs are specific to the conventions of the 1974 to 2000 NFS data collection process. Ingestion of other similar dietary data would not automatically work with those scripts. 

That said, modifications to the ingestion and aggregation scripts could facilitate ingestion of applicable similar data. Once ingested and aggregated according to the feature engineering steps described above, harmonizable diet data from other sources (the UK in later years, the United States, or other countries) could be integrated into the analysis.  If appropriately prepared, it could potentially be clustered by the ML pipeline in this project and analyzed downstream as if it were from the original data.

The chronic disease data from the GBD Results tool is easily scalable, and compatible chronic disease SEV data for other developed nations could be obtained and integrated into this analysis.  

All that said, due diligence would be required to make sure any new dietary data was actually harmonizable, and potential external confounding factors would have to be sought and ruled out.


