# Methods

### Software and Tools

All data engineering, analysis, and visualization were conducted in Python 3.13.7 and R 4.5.1.

Python packages that were used in the final analysis include pandas and numpy for basic data manipulation, scikit-learn for PCA and k-means clustering, and matplotlib, seaborn and geopandas for visualization.  R packages that were used in the final analysis include tidyverse for data manipulation, rstatix/coin for statistical testing, and ggplot2 for visualization. 

### Principal component analysis

Z-scored household diet data was subjected to dimensionality reduction in both the food group dimension space and the nutrient dimension space using principal component analysis, or PCA.  PCA finds the multi-dimensional axis of greatest variance for all the data in a dataset, and multiple iterations of PCA can cumulatively explain increasing amounts of variance in the data.  

For both food group and nutrients dimension spaces, PCA was successively run until 95% of the variance was explained.  

The top two most explanatory principal components (PC 1 and PC 2) for each analysis were plotted in order of their linear combination weights for the given dimensions, producing a human interpretable orientation for that component.


### Best k selector for k-means clustering

In k-means clustering, data points are categorized into *k*  number of clusters, based on data point distance from moving cluster centroids across many initializations of the algorithm. Any target number of clusters could be arbitrarily selected, but rigorous analysis requires a more careful process to select the most stable number of clusters for the data.

In order to select the most stable number of clusters in a rigorous manner, a cross-validation cluster stability overlap function was constructed and named `best-k-selector`. In this algorithm, a random sample of the data points is selected and subjected to k-means clustering in successive rounds with the number of clusters increasing iteratively upwards from two.  Each round involves 80% of the sample being subsampled, clustered, replaced, and then a fresh 80% subsample (with many of the same data points) being clustered at the same number of clusters.  The clustered subsampled data points are compared for overlapping labels. The percentage of datapoints with overlapping cluster labels between the two subsamples is called the Adjusted Rand Index, or ARI score.  

The `best-k-selector` repeats the process as it sweeps from two clusters upward as many times as instructed.  Eventually, the ARI scores for each number of clusters is averaged, and the number of clusters with the highest average ARI amongst all repeats is considered the 'best k' number of clusters for that dataset.


### k-means clustering

Once the 'best k' number of clusters was consistently discovered for food group and nutrient dimensions, clustering of all households in the data could take place.  

The k-means clustering algorithm places the desired number of cluster centroids randomly in the data, assigns each data point a cluster label based on the nearest centroid, shifts the centroids to the average position of their respective assigned data points.  This is repeated over and over until the centroids effectively stop moving. The k-means algorithm reinitializes numerous times (hundreds or more) to assess cluster label consistency before determining the final designated cluster labels for each data point.


### PCA to visualize clusters

In order to visualize household cluster labels from 16-dimensional food group space or 20-dimensional nutrient space, the principal components required to cumulatively explain 95% of variance of the data were put through an additional round of PCA, this time aiming for exactly two new principal components. These new components were used as the X and Y axes along which to plot all households in a 2-dimensional scatter plot projection.  

This double PCA approach does not directly inform the k-means clustering, but it does allow the datapoints to be visualized in human-friendly two dimensions, and along reasonably human-interpretable axes.


### PCA used for heat map interpretation

Heatmaps are used to visualize the z-scores of cluster centroids.

The most explanatory principal components (PC 1 and PC 2) from upstream analysis are used to order the axes of heatmaps for each cluster.

### Cluster proportions over time

Analysis of changes in the proportions of clusters over time was conducted using two proportion z-tests, Cochran-Armitage tests, and Kendall Tau Trend tests. Additionally, the cluster proportions were visualized as lineplots. 

The two proportion z-test was applied to each pair of consecutive survey years for every cluster. This provided a localized check of significant changes from one year to the next. This test was chosen because it made no assumption about the change of the shape overtime. It was able to catch short-term shifts that a broader trend test may miss or average out. It was also leveraged to identify and validate statistical changes over the course of the time span which could then be addressed later.

Because the two proportion z-tests are not meant to characterize a trend across the 27 year period, the Cochran-Armitage test was applied to cover this shortfall. It was applied to each cluster's proportion change over the full time frame. The test was specifically selected because cluster membership was effectively binary at each point in time and the survey years followed a chronological order so the conditions were optimal for this test. Once more, it was used to determine if a cluster's proportion moved consistently in one direction across the study as opposed to looking at noise driven changes.

The Kendall's tau rank correlation was introduced as a distribution-free companion check for the Cochran-Armitage test which relies on a count-based and approximately linear structure. When these two tests agree on the direction and significance of a trend, that agreement acts as strengthened confidence that such a pattern is genuine.

### Cross correlation function (CCF) for time lag

After k-means clustering, each UK region's proportion of each assigned cluster per year was exported into a parquet file, which was loaded into a new pandas dataframe. That dataframe was extended with many lag year columns onto which IHME disease SEV data could be joined on region and year, with given diet data lag years corresponding to an IHME disease SEV actual years. 

This enabled rate of change correlation assessment, with year-on-year changes in cluster proportions and in SEV for a given metabolic risk being assigned a Pearson correlation coefficient *r*, with high correlation being closer to 1, and no correlation being closer to zero.

The main explanatory variable (changes in population-level proportion of a particularly plant-oriented nutrient cluster over time) and the main response variable (changes in SEV for High LDL cholesterol) were specifically selected based on their visual appearance in lineplots (@fig-R-line and @fig-metabolic-rates-over-time-all-region), and not based on more rigorous mathematical means. 

This is noted in the Methods section because an important part of this lag correlation analysis is that it was primarily informed by a visibly remarkable pair of trends in the lineplots. 

### Correlation validation

After identifying statistically significant correlation between the explanatory and response variables at a particular time lag, the order of SEV rates by year was held constant, and tested for correlation against thousands of permutations of the pertinent diet cluster data years. If the identified correlation was actually a product of random chance, it would be expected that other permutations of the data would randomly produce similar appearance of correlation some of the time.

Additionally and finally, correlation rates at the identified time lag were plotted in a choropleth of the UK, showing how consistently nutrient cluster proportion changes and metabolic risk factor SEVs are correlated at the identified time lag over the time span of the data.