# Conclusions


### Overall conclusion

There appears to be a statistically-significant inverse correlation between year-on-year changes in population proportion of nutrient-profile Cluster 2 and year-on-year changes in population-level high LDL cholesterol SEV scores, at a five-year time lag. Nutrient profile cluster 2 is characterized by higher levels of nutrients most associated with plant-based foods, so we conclude that there appears to be a detectable time-lagged correlative association between increasing plant-based food trends and lowering LDL cholesterol rates in the UK population. 

Of course, this is consistent with years of literature and medical advice.  The innovation of this project, if any, is the identification of the five-year time lag specifically. This information is potentially useful to any individual tracking their own health, and to public health officials assessing the effectiveness of policies related to food and metabolic disease. 

### Limitations

The most significant limitation of this study is that it is not longitudinal.  It would be ideal to track high numbers of individual people in a scientifically controlled manner, over many years of analysis. In that case, varying dietary habits and health outcomes could be mapped to individual people and then aggregated for statistical power.  Unfortunately, longitudinal data like this is rare and hard to obtain.  So, the best option for this realm of investigation was to find aggregatable data with large numbers of subjects, and to make statistically cautious population level claims from there.  Future investigation in this direction would be buoyed by access to longitudinal diet and health data.

Another limitation is that there are many confounding variables involved in human health outcomes: genetics, poverty, food access, education, environmental exposures, other lifestyle factors, and more. A strong proclamation about the universal applicability of this finding is not warranted.  
 
Beyond that, there is the fact that the diet diaries were self-reported.  There could be inconsistencies, inaccuracies, and intentional misrepresentations included in the data.  The impact of this limitation might be mitigated in our study by the fact that such potential data unreliability would likely have been consistent, if existent. That is to say that if people are bad at being accurate about tracking what they bought to eat, they probably used to be bad at that in the past as well. If so, that unreliability is consistent, and so an analysis based on relative changes over time might still be viable.
 
Additionally, the diet diaries tracked quantities of consumable food that was purchased. It is assumed that all of this purchased food was actually consumed, but that could be inaccurate.  People might have bought food and not eaten it, meaning the inferred correlation between diet and disease might be somewhat miscalculated.  While this cannot be ruled out, it does bear suggestion that many people are budget conscious, and might actively avoiding wasting money on food they will not eat.
 
Relatedly though, some households might be bulk shoppers who buy a lot of food every other week, or every month. For such a bulk shopping household, the timing of the diet diary week could make them appear to consume way too much or way too little. Those who reported buying nothing might have been pruned by the calorie filter, but those who reported buying a large amount might erroneously seem to be gluttons, skewing calculated aggregations.

A final limitation of this correlative analysis is that, based on the timeframes of the available diet and disease data, there were a limited number of overlapping years to assess.  Based on the five-year-time lag, there were only 15 analyzable years, and n = 15 is not ideal.  However, compared on the lack of any apparent correlation when other clusters and disease risk factors were analyzed in a similar manner, the discovered correlation reported herein is not entirely discountable.

### Final thoughts

Human health and its association with diet are complex.

Any additional insight into connections between food and health can bolster individuals and society to improve their longevity and reduce their risk of chronic disease.  While there are mixed messages from online influencers about these food-health connections, this analysis suggests that mainstream medical messaging is likely right: a more plant-based diet might help lower LDL cholesterol. 
 
To be very clear, this study makes no claims about diet and health for individual people. 

That said, this study does conclude that, at least in the UK from 1985 to 2000, there was a statistically significant correlation between the year-on-year change in population proportion of a relatively plant-based nutrient-profile cluster (as designated by k-means clustering) and the year-on-year change in population-level high LDL cholesterol SEV score. 

