# References

:::{#refs}
Peng, Ke, Xingyue Li, Zhen Wang, Meiling Li, and Yongjian Yang. \uc0\u8220{}Association of Low-Density Lipoprotein Cholesterol Levels with the Risk of Mortality and Cardiovascular Events: A Meta-Analysis of Cohort Studies with 1,232,694 Participants.\uc0\u8221{} {\i{}Medicine} 101, no. 48 (2022): e32003. https://doi.org/10.1097/MD.0000000000032003.\


Schoeneck, Malin, and David Iggman. \uc0\u8220{}The Effects of Foods on LDL Cholesterol Levels: A Systematic Review of the Accumulated Evidence from Systematic Reviews and Meta-Analyses of Randomized Controlled Trials.\uc0\u8221{} {\i{}Nutrition, Metabolism, and Cardiovascular Diseases: NMCD} 31, no. 5 (2021): 1325\uc0\u8211{}38. https://doi.org/10.1016/j.numecd.2020.12.032.\


Schwind, Bettina, Rosa Visscher, J\uc0\u246{}rg Haslbeck, et al. \uc0\u8220{}Understanding Family Caregiving and Well-Being in Adult Chronic Illness: A Call for a More Comprehensive Perspective.\uc0\u8221{} {\i{}Frontiers in Public Health} 13 (September 2025): 1619672. https://doi.org/10.3389/fpubh.2025.1619672.\


Zhang, Frank, Ronac Mamtani, Frank I. Scott, David S. Goldberg, Kevin Haynes, and James D. Lewis. \uc0\u8220{}Increasing Use of Prescription Drugs in the United Kingdom.\uc0\u8221{} {\i{}Pharmacoepidemiology and Drug Safety} 25, no. 6 (2016): 628\uc0\u8211{}36. https://doi.org/10.1002/pds.3947.\
N.d.\


:::